name: BetterAlias
main: com.gmail.Ne0nx3r0.BetterAlias
version: '0.5'
database: false
description: Command alias system
commands:
   bareload:
      description: Reloads the aliases.yml file
permissions:
    BetterAlias.reload:
      description: Allows reloading BetterAlias