name: BetterAlias
main: com.ne0nx3r0.betteralias.BetterAlias
version: '1.5.2'
database: false
description: Command alias system
commands:
   bareload:
      description: Reloads the aliases.yml file
permissions:
    BetterAlias.reload:
      description: Allows reloading BetterAlias