name: BetterAlias
main: com.ne0nx3r0.betteralias.BetterAlias
version: '2.0'
database: false
description: Command alias system
commands:
   bareload:
      description: Reloads the aliases.yml file   
   badonothing:
      description: Filler command, since console commands are not cancellable
permissions:
    BetterAlias.reload:
      description: Allows reloading BetterAlias